# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty

# environment
env:
  global:
    - LLVM_VERSION=5.0
    - CLANG_VERSION=5.0
    - CC=gcc-7
    - CXX=g++-7

# language spec
language: python
python:
  - "2.7"
  - "3.6"

# install dependencies
before_install:
  # add new gcc toolchains
  - sudo apt-add-repository ppa:ubuntu-toolchain-r/test
  # get llvm key
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  # add repo
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
  # update
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7 gcc-7 clang-5.0 clang-5.0-doc libclang-common-5.0-dev libclang-5.0-dev libclang1-5.0 libclang1-5.0-dbg libllvm-5.0-ocaml-dev libllvm5.0 libllvm5.0-dbg lldb-5.0 llvm-5.0 llvm-5.0-dev llvm-5.0-doc llvm-5.0-examples llvm-5.0-runtime clang-format-5.0 python-clang-5.0 lldb-5.0-dev lld-5.0 libfuzzer-5.0-dev libltdl3-dev libhwloc-dev cmake3 git
  # openmp
  - export OMP_NUM_THREADS=4
  # go up to start cloning from git
  - cd ..
  - git clone https://github.com/OCL-dev/ocl-icd
  # build OCL-ICD
  - cd ocl-icd
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - cd ../
  # build pocl
  - git clone https://github.com/pocl/pocl
  - cd pocl/
  - mkdir build && cd build
  - cmake3 ..
  - make
  - sudo make install
  - cd ../
  # and go back to pyjac
  - cd spyJac

# install pyjac
install:
  # currently need the newest loopy version
  - pip install git+https://github.com/inducer/loopy.git
  - pip install -r requirements.txt --user
  - pip install -r optional-requirements.txt --user
  - pip install . --user

# run test
script:
  - nosetests -a '!verylong' -s
