# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty

# environment
env:
  global:
    - CC=gcc-7
    - CXX=g++-7
    - PRIORITY=500
    - LLV=5.0

# language spec
language: python
python:
  - "2.7"
  - "3.6"

# install dependencies
before_install:
  # add new gcc toolchains
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  # get llvm key
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  # add repo
  - sudo apt-add-repository -y "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-$LLV main"
  # update
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-7 gcc-7 clang-$LLV clang-$LLV-doc libclang-common-$LLV-dev libclang-$LLV-dev libclang1-$LLV libclang1-$LLV-dbg libllvm$LLV libllvm$LLV-dbg lldb-$LLV llvm-$LLV llvm-$LLV-dev llvm-$LLV-doc llvm-$LLV-examples llvm-$LLV-runtime clang-format-$LLV python-clang-$LLV lld-$LLV libfuzzer-$LLV-dev libltdl3-dev libhwloc-dev cmake3 git
  # and finally update alternatives
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 $PRIORITY
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 $PRIORITY
  - sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-$LLV $PRIORITY
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-$LLV $PRIORITY
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - sudo update-alternatives --config llvm-config
  - sudo update-alternatives --config clang
  # openmp
  - export OMP_NUM_THREADS=4
  # go up to start cloning from git
  - cd ..
  - git clone https://github.com/OCL-dev/ocl-icd
  # build OCL-ICD
  - cd ocl-icd
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - cd ../
  # build pocl
  - git clone https://github.com/pocl/pocl
  - cd pocl/
  - mkdir build && cd build
  - cmake -DWITH_LLVM_CONFIG=`which llvm-config` ..
  - make
  - sudo make install
  - cd ../
  # and go back to pyjac
  - cd arghdos/spyJac

# install pyjac
install:
  # currently need the newest loopy version
  - pip install git+https://github.com/inducer/loopy.git
  - pip install -r requirements.txt --user
  - pip install -r optional-requirements.txt --user
  - pip install . --user

# run test
script:
  - nosetests -a '!verylong' -s
