# Use new trusty images, should yield newer compilers and packages
sudo: required
dist: trusty

# environment
env:
  global:
    - LLVM_VERSION=5.0
    - CLANG_VERSION=5.0

# language spec
language: python
python:
  - "2.7"
  - "3.6"

apt:
  sources:
    - sourceline: 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main'
    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
  packages:
    - clang-5.0
    - llvm-5.0-dev
    - gcc-8
    - g++-8
    - libltdl3-dev
    - libhwloc-dev
    - cmake3
    - git

# install dependencies
before_install:
  # setup compilers
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - export CC=gcc
  - export CXX=g++
  # go up to start cloning from git
  - cd ..
  - git clone https://github.com/OCL-dev/ocl-icd
  # build OCL-ICD
  - cd ocl-icd
  - ./bootstrap
  - ./configure
  - make
  - sudo make install
  - cd ../
  # build pocl
  - git clone https://github.com/pocl/pocl
  - cd pocl/
  - mkdir build && cd build
  - cmake3 ..
  - make
  - sudo make install
  - cd ../
  # and go back to pyjac
  - cd spyJac

# install pyjac
install:
  # currently need the newest loopy version
  - pip install git+https://github.com/inducer/loopy.git
  - pip install -r requirements.txt --user
  - pip install -r optional-requirements.txt --user
  - pip install . --user

# run test
script:
  - nosetests -a '!verylong' -s
